openapi: 3.0.0
info:
  title: Docs API IClubs.io
  description: Documentation to API Letters to Santa.
  version: 0.1.0
servers:
  - url: http://localhost:3333/api/v1
    description: server for testing

components:
  securitySchemes:
     bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Token is missing or invalid !

tags:
- name: "santa"
  description: "Papai Noel"

- name: "letters"
  description: "CRUD Cartas"

  
paths:
  /santa/new:
    post:
      tags: 
      - "santa"
      summary: "Criar um novo Login"
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - login
                - password
              properties: 
                login: 
                  type: string
                password: 
                  type: string
                  
      responses:
        "201":
          success: true
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /santa/login:
    post:
      tags: 
      - "santa"
      summary: "Fazer login"
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - login
                - password
              properties: 
                login: 
                  type: string
                password: 
                  type: string
                  
      responses:
        "201":
          success: true
        "401":
          $ref: "#/components/responses/UnauthorizedError"


  /letter/new:
    post:
      tags: 
      - "letters"
      summary: "Enviar uma carta"
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - "first_name"
                - "last_name"
                - "address"
                - "zip_code"
                - "state"
                - "city"
                - "country"
                - "body_letter"
              properties: 
                first_name: 
                  type: "string"
                last_name: 
                  type: "string"
                address: 
                  type: "string"
                zip_code: 
                  type: "string"
                state: 
                  type: "string"
                city: 
                  type: "string"
                country: 
                  type: "string"
                body_letter: 
                  type: "string"

                  
      responses:
        "201":
          success: true
        "400":
          description: "Internal server error"

  /letter:
    get:
      tags: 
      - "letters"
      summary: "Lista todas as cartas"
      security:
        - bearerAuth: []
      application/json:          
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Letter"      
        "401":
          $ref: "#/components/responses/UnauthorizedError"


  /letter/approved/{letter_id}:
    put:
      tags: 
      - "letters"
      summary: "Atualizar status para aprovada"
      security:
        - bearerAuth: []
      parameters: 
        - in: path
          name: letter_id
          description: "Id carta"
          schema:
            type: string
          required: true  
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - approved
              properties: 
                approved: 
                  type: "boolean"                
      responses:
        "200":
          description: "Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      
  /letter/read/{letter_id}:
    put:
      tags: 
      - "letters"
      summary: "Atualizar status para lida"
      security:
        - bearerAuth: []
      parameters: 
        - in: path
          name: letter_id
          description: "Id carta"
          schema:
            type: string
          required: true  
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - read
              properties: 
                read: 
                  type: "boolean"                
      responses:
        "200":
          description: "Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /letter/read:
    get:
      tags: 
      - "letters"
      summary: "Listar todas as cartas lidas"
      security:
        - bearerAuth: [] 
               
      responses:
        "200":
          description: "Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /letter/read/not:
    get:
      tags: 
      - "letters"
      summary: "Listar todas as cartas não lidas"
      security:
        - bearerAuth: [] 
               
      responses:
        "200":
          description: "Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      


  /letter/approved:
    get:
      tags: 
      - "letters"
      summary: "Listar todas cartas as aprovadas"
      security:
        - bearerAuth: [] 
               
      responses:
        "200":
          description: "Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      

  /letter/approved/not:
    get:
      tags: 
      - "letters"
      summary: "Listar todas as cartas não aprovadas"
      security:
        - bearerAuth: [] 
               
      responses:
        "200":
          description: "Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
      

  /letter/delete/{letter_id}:
    delete:
      tags: 
      - "letters"
      summary: "Deletar uma carta"
      security:
        - bearerAuth: []
      parameters: 
        - in: path
          name: letter_id
          description: "Id carta"
          schema:
            type: string
          required: true             
      responses:
        "200":
          description: "Success"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

definitions:
  Letter:
    type: "object"
    properties:
      id: 
        type: "string" 
      was_read: 
        type: "boolean"
      approved: 
        type: "boolean"
      first_name: 
        type: "string"
      last_name: 
        type: "string"
      address: 
        type: "string"
      zip_code: 
        type: "string"
      state: 
        type: "string"
      city: 
        type: "string"
      country: 
        type: "string"
      body_letter: 
        type: "string"
      create_at:
        type: "date-time"