openapi: 3.0.0
info:
  title: Docs API IClubs.io
  description: Documentation to API Letters to Santa.
  version: 0.1.0
servers:
  - url: http://localhost:3333/v1
    description: server for testing

components:
  securitySchemes:
     bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Token is missing or invalid !

tags:
- name: "santa"
  description: ""

- name: "letters"
  description: "CRUD Letters"

  
paths:
  /santa/new:
    post:
      tags: 
      - "santa"
      summary: "Create a login"
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - login
                - password
              properties: 
                login: 
                  type: string
                password: 
                  type: string
                  
      responses:
        201:
          success: true
        401:
          $ref: "#/components/responses/UnauthorizedError"

  /santa/login:
    post:
      tags: 
      - "santa"
      summary: "Authenticate with valid login"
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - login
                - password
              properties: 
                login: 
                  type: string
                password: 
                  type: string
                  
      responses:
        201:
          success: true
        401:
          $ref: "#/components/responses/UnauthorizedError"


  /letter/new:
    post:
      tags: 
      - "letters"
      summary: "Send a new letter"
      security:
        - bearerAuth: []
      requestBody:
        content: 
          application/json:
            schema:
              type: "object"
              required:
                - first_name
                - last_name
                - address
                - zip_code
                - state
                - city
                - country
                - body_letter
              properties: 
                first_name: 
                  type: string
                last_name: 
                  type: string
                address: 
                  type: string
                zip_code: 
                  type: string
                state: 
                  type: string
                city: 
                  type: string
                country: 
                  type: string
                body_letter: 
                  type: string

                  
      responses:
        201:
          success: true
        401:
          $ref: "#/components/responses/UnauthorizedError"
      
     